@PropertyManagement_ApiHostAddress = http://localhost:5247

### GET
GET {{PropertyManagement_ApiHostAddress}}/api/buildings
Accept: application/json

### POST
POST {{PropertyManagement_ApiHostAddress}}/api/buildings
Content-Type: application/json

{
    "name": "Tony Street",
    "address": "105 Marshall Dr",
    "numberOfUnits": 10
}

### PUT/UPDATE

PUT {{PropertyManagement_ApiHostAddress}}/api/buildings/1
Content-Type: application/json

{
    "name": "Updated Building",
    "address": "New Address",
    "numberOfUnits": 99
}

###
DELETE {{PropertyManagement_ApiHostAddress}}/api/buildings/1 

### ### Verify it was deleted 
GET {{PropertyManagement_ApiHostAddress}}/api/buildings 
Accept: application/json

