@BuildingManagement_ApiHostAddress = http://localhost:5247

GET {{BuildingManagement_ApiHostAddress}}/api/buildings
Accept: application/json

###

POST http://localhost:5247/api/buildings
Content-Type: application/json

{
    "name": "Downtown Plaza",
    "address": "123 Main Street",
    "numberOfUnits": 50
}

###

PUT http://localhost:5247/api/buildings/1
Content-Type: application/json

{
    "name": "Updated Building",
    "address": "New Address",
    "numberOfUnits": 99
}